import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';

export type HookAgent = 'pi' | 'codex';

export interface HookInstallResult {
  agent: HookAgent | 'claude' | 'opencode';
  status: 'installed' | 'merged' | 'kept' | 'skipped' | 'failed';
  path?: string;
  reason?: string;
}

export function installDetectedHooks(binCommand: string, home = homedir()): HookInstallResult[] {
  return [
    installPiHook(binCommand, home),
    installCodexHook(binCommand, home),
    detectOnly('claude', join(home, '.claude')),
    detectOnly('opencode', join(home, '.config', 'opencode')),
  ];
}

export function installPiHook(binCommand: string, home = homedir()): HookInstallResult {
  const extensionsDir = join(home, '.pi', 'agent', 'extensions');
  const path = join(extensionsDir, 'herdr-trace.ts');
  if (!existsSync(dirname(extensionsDir))) {
    return { agent: 'pi', status: 'skipped', path, reason: 'Pi agent directory not detected' };
  }
  try {
    mkdirSync(extensionsDir, { recursive: true });
    const contents = piExtensionTemplate(binCommand);
    if (existsSync(path) && readFileSync(path, 'utf8') === contents) {
      return { agent: 'pi', status: 'kept', path };
    }
    writeFileSync(path, contents);
    return { agent: 'pi', status: 'installed', path };
  } catch (error) {
    return { agent: 'pi', status: 'failed', path, reason: errorMessage(error) };
  }
}

export function installCodexHook(binCommand: string, home = homedir()): HookInstallResult {
  const codexDir = join(home, '.codex');
  const path = join(codexDir, 'hooks.json');
  if (!existsSync(codexDir)) {
    return { agent: 'codex', status: 'skipped', path, reason: 'Codex config directory not detected' };
  }
  try {
    const existing = existsSync(path) ? JSON.parse(readFileSync(path, 'utf8')) as unknown : {};
    const merged = mergeCodexHooks(existing, binCommand);
    const next = `${JSON.stringify(merged.value, null, 2)}\n`;
    if (existsSync(path) && readFileSync(path, 'utf8') === next) {
      return { agent: 'codex', status: 'kept', path };
    }
    writeFileSync(path, next);
    return { agent: 'codex', status: merged.changed ? 'merged' : 'kept', path };
  } catch (error) {
    return { agent: 'codex', status: 'failed', path, reason: errorMessage(error) };
  }
}

export function mergeCodexHooks(existing: unknown, binCommand: string): { value: Record<string, unknown>; changed: boolean } {
  const root = isRecord(existing) ? { ...existing } : {};
  let changed = !isRecord(existing);
  for (const event of ['SessionStart', 'PreToolUse', 'PostToolUse', 'Stop']) {
    const current = Array.isArray(root[event]) ? [...root[event] as unknown[]] : [];
    const hook = { command: `${binCommand} trace-hook --event ${event} --agent codex` };
    const exists = current.some((item) => isRecord(item) && item.command === hook.command);
    if (!exists) {
      current.push(hook);
      changed = true;
    }
    root[event] = current;
  }
  return { value: root, changed };
}

function detectOnly(agent: 'claude' | 'opencode', path: string): HookInstallResult {
  return existsSync(path)
    ? { agent, status: 'skipped', path, reason: 'hook installer not implemented yet' }
    : { agent, status: 'skipped', path, reason: 'agent config directory not detected' };
}

function piExtensionTemplate(binCommand: string): string {
  const command = JSON.stringify(binCommand);
  return `// Generated by herdr-worktree-dispatcher install.\n// Forwards Pi agent lifecycle and tool events to the dispatcher trace collector.\n\nconst HERDR_TRACE_COMMAND = ${command};\n\nfunction runTraceHook(event: string, payload: unknown) {\n  const traceFile = process.env.HERDR_TRACE_FILE;\n  if (!traceFile) return;\n  try {\n    const childProcess = require(\"node:child_process\");\n    childProcess.spawnSync(\"sh\", [\"-lc\", HERDR_TRACE_COMMAND + \" trace-hook --event \" + shellQuote(event) + \" --agent pi\"], {\n      input: JSON.stringify(payload ?? {}),\n      encoding: \"utf8\",\n      stdio: [\"pipe\", \"ignore\", \"ignore\"],\n    });\n  } catch {\n    // Tracing must never interrupt the agent.\n  }\n}\n\nfunction shellQuote(value: string) {\n  return \"'\" + String(value).replace(/'/g, \"'\\\\''\") + \"'\";\n}\n\nexport default function herdrTraceExtension(ctx: any) {\n  const sessionPayload = () => ({\n    session_id: ctx?.sessionManager?.getSessionId?.(),\n    session_path: ctx?.sessionManager?.getSessionFile?.(),\n  });\n\n  ctx?.hooks?.on?.(\"session_start\", (payload: unknown) => runTraceHook(\"session_start\", { ...sessionPayload(), ...(payload as object || {}) }));\n  ctx?.hooks?.on?.(\"agent_start\", (payload: unknown) => runTraceHook(\"agent_start\", { ...sessionPayload(), ...(payload as object || {}) }));\n  ctx?.hooks?.on?.(\"agent_end\", (payload: unknown) => runTraceHook(\"agent_end\", { ...sessionPayload(), ...(payload as object || {}) }));\n  ctx?.hooks?.on?.(\"tool_execution_start\", (payload: unknown) => runTraceHook(\"tool_execution_start\", { ...sessionPayload(), ...(payload as object || {}) }));\n  ctx?.hooks?.on?.(\"tool_execution_end\", (payload: unknown) => runTraceHook(\"tool_execution_end\", { ...sessionPayload(), ...(payload as object || {}) }));\n}\n`;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === 'object' && !Array.isArray(value);
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}
